### ISSUE TITLE
[spam] Guides-templete

### ISSUE THREAD

**Issue by notebook-t** [moodle/devdocs#1049]
[templetes](https://github.com/moodle/devdocs/blob/main/docs%2Fguides%2Ftemplates%2Findex.md)

# {{ mustache }}

Clipped from: https://mustache.github.io

## Excerpt

> Logic-less templates.

Logic-less templates.

Available in [Ruby](https://github.com/mustache/mustache), [JavaScript](https://github.com/janl/mustache.js), [Python](https://github.com/noahmorrison/chevron), [Erlang](https://github.com/mojombo/mustache.erl), [Elixir](https://github.com/schultyy/Mustache.ex), [PHP](https://github.com/bobthecow/mustache.php), [Perl](https://github.com/pvande/Template-Mustache), [Raku](https://github.com/softmoth/p6-Template-Mustache), [Objective-C](https://github.com/groue/GRMustache), [Java](https://github.com/spullara/mustache.java), [C#/.NET](https://github.com/StubbleOrg/Stubble), [Android](https://github.com/samskivert/jmustache), [C++](https://github.com/no1msd/mstch), [CFEngine](https://github.com/cfengine/core), [Go](https://github.com/cbroglie/mustache), [Lua](https://github.com/Olivine-Labs/lustache), [ooc](https://github.com/joshthecoder/mustang), [ActionScript](https://github.com/hyakugei/mustache.as), [ColdFusion](https://github.com/pmcelhaney/Mustache.cfc), [Scala](https://github.com/scalate/scalate), [Clojure\[Script\]](https://github.com/fotoetienne/cljstache), [Clojure](https://github.com/fhd/clostache), [Fantom](https://github.com/vspy/mustache), [CoffeeScript](https://github.com/pvande/Milk), [D](https://github.com/repeatedly/mustache-d), [Haskell](https://github.com/JustusAdam/mustache), [XQuery](https://github.com/dscape/mustache.xq), [ASP](https://github.com/nagaozen/asp-xtreme-evolution/blob/master/lib/axe/classes/Parsers/mustache.asp), [Io](https://github.com/mil/mustache.io), [Dart](https://github.com/valotas/mustache4dart), [Haxe](https://github.com/nadako/hxmustache), [Delphi](https://github.com/synopse/dmustache), [Racket](https://github.com/rcherrueau/rastache), [Rust](https://github.com/nickel-org/rust-mustache), [OCaml](https://github.com/rgrinberg/ocaml-mustache), [Swift](https://github.com/groue/GRMustache.swift), [Bash](https://github.com/tests-always-included/mo), [Julia](https://github.com/jverzani/Mustache.jl), [R](https://github.com/edwindj/whisker), [Crystal](https://github.com/MakeNowJust/crustache), [Common Lisp](https://github.com/kanru/cl-mustache/), [Nim](https://github.com/fenekku/moustachu), [Pharo](https://github.com/noha/mustache), [Tcl](https://github.com/ianka/mustache.tcl), [C](https://gitlab.com/jobol/mustach), [ABAP](https://github.com/sbcgua/abap_mustache), [Elm](https://github.com/truqu/elm-mustache), [Kotlin](https://github.com/cashapp/barber), [SQL](https://github.com/microtangents/sql-mustache), [PowerShell](https://github.com/splumhoff/PSMustache), [Odin](https://github.com/benjamindblock/odin-mustache), and for [Arduino](https://github.com/floatplane/ministache)

Works great with [TextMate](https://gist.github.com/323624), [Vim](https://github.com/mustache/vim-mustache-handlebars), [Emacs](http://web-mode.org), [Coda](https://github.com/bobthecow/Mustache.mode), and [Atom](https://github.com/atom/language-mustache)

The Manual: [mustache(5)](https://mustache.github.iomustache.5.html) and [mustache(1)](https://mustache.github.iomustache.1.html)

[Specification](https://github.com/mustache/spec)

[Playground](https://jgonggrijp.gitlab.io/wontache/playground.html)

Chat: [+mustache:matrix.org](https://matrix.to/#/!dEINhhFQbxrzfECZpc:matrix.org?via=matrix.org) on Matrix.org

GitHub pages: [https://github.com/mustache/mustache.github.com](https://github.com/mustache/mustache.github.com)

**Comment by andrewnicols** [comment]
SPAM
