### ISSUE TITLE
[spam] Moodle Developers Resourves

### ISSUE THREAD

**Issue by notebook-t** [moodle/devdocs#1050]
# Getting started | Moodle Developer Resources

Clipped from: https://moodledev.io/general/development/gettingstarted

## Excerpt

> - Set up your development environment

# Getting started

## A quick start to Moodle development[​](#a-quick-start-to-moodle-development "Direct link to A quick start to Moodle development")

1.  Create an account on [Moodle.org](https://moodle.org/). You will need this to access the [Moodle General Developer forum](https://moodle.org/mod/forum/view.php?f=33) and download [Moodle plugins](https://moodle.org/plugins). You can also sign up to free self-paced courses in our [Moodle Academy Developer Learning Pathway](https://moodle.academy/course/index.php?categoryid=4)
2.  Create an account on [GitHub](https://github.com/) and [install Git on your computer](https://moodledev.io/docs/4.5/guides/git). This is the source code version control repository tool of choice for Moodle development.
3.  [Install Moodle on your machine](https://docs.moodle.org/en/Installing_Moodle) or use a container environment like [moodle-docker](https://github.com/moodlehq/moodle-docker). You can also use [Moodle Development Kit (MDK)](https://moodledev.io/general/development/tools/mdk).

tip

We highly recommend that you use a database administration tool such as [adminer](https://www.adminer.org/) to help you manage your development databases.

1.  Set-up Moodle for development:

-   Enable the [Moodle Debugger](https://docs.moodle.org/en/Debugging).
    
    tip
    
    When developing in Moodle, it's recommended to turn debugging on. Only turn it off for demonstration purposes as it does have a considerable impact on the performance of your Moodle website.
    
    Attention
    
    Always resolve all errors and warnings that show up with **Moodle debugging turned on**. Errors and warnings imply that something isn't working as it is supposed to which means your code isn't doing what you intended it to, or may be fragile and could break in the future.
    
-   Install the [Moodle PHP CodeSniffer](https://moodledev.io/general/development/tools/phpcs). This will be used to test your plugin for conformance with Moodle coding standards. Use this to develop good coding skills.
    
-   Install the Moodle [PHPdoc check plugin](https://moodle.org/plugins/local_moodlecheck). This will be used to test your source code documentation. This will also help improve your coding skills.
    
    Advanced
    
    You can use Xdebug to enable step-by-step debugging in PHP. Integrations are built into many popular editors. [Learn more](https://moodledev.io/docs/4.5/guides/profiling#xdebug)
    

And finally remember these wise words from [Michael Milette](https://moodle.org/user/view.php?id=1615960&course=5) in the [General developer forum](https://moodle.org/mod/forum/discuss.php?d=355789):

> Learning how to code in Moodle involves a lot of learning by example and reading other people's source code including Moodle core code. If you have a particular type of plugin in mind that you would like to create, it's recommended that you start by finding a plugin which provides similar functionality and use the process outlined above to clone it. Then customize it to suit your needs. You can even do this with 3rd party plugins found on the [plugins directory](https://moodle.org/plugins). That's just one of the many advantages of developing with open source. Just always remember to give credit to the original author for his/her original hard work. \[...\]
> 
> Learning all of Moodle and its database takes time - maybe even years. In fact you may never come across parts of it and that's OK. Take it one step at a time and don't be afraid to ask for help when you get stuck. The only expectation by the worldwide community is that you will have tried to figure things out on your own before asking a question. Google is your friend. Just start your query with the word "moodle".

## Communication[​](#communication "Direct link to Communication")

If you have any question or want to share your ideas, there are several channels you can use to communicate with other developers:

-   [Moodle community forums](https://moodle.org/course/), available in different languages.
-   [A Matrix room](https://matrix.to/#/%23moodledev:moodle.com) available for real-time communication. Read the [chat policies](https://docs.moodle.org/dev/Chat) before joining.
-   [Developer meetings](https://moodledev.io/general/community/meetings), organised periodically and open to anyone interested in Moodle development.

## Developer FAQ[​](#developer-faq "Direct link to Developer FAQ")

Visit our [Developer FAQ](https://moodledev.io/general/development/abc/faq) page and get answers to some of our most common questions.

## See also[​](#see-also "Direct link to See also")

-   [Releases](https://moodledev.io/general/releases) \- versions of Moodle that have already been released
-   [Process](https://moodledev.io/general/development/process)
-   [API guides](https://moodledev.io/docs/4.5/apis)
-   [Contributing](https://moodledev.io/general/community/contribute)
-   [A (july 2017) forum thread](https://moodle.org/mod/forum/discuss.php?d=355789) about Getting Started with Moodle Development.

**Comment by notebook-t** [comment]
---
created: 2024-06-16T05:29:30
source: https://tracker.moodle.org/issues/
author: 
---

# Loading...

Clipped from: https://tracker.moodle.org/issues/

## Excerpt

> [{"id":-1,"name":"My open issues","jql":"assignee = currentUser() AND resolution = Unresolved order by updated DESC","isSystem":true,"sharePermissions":[],"requiresLogin":true},{"id":-2,"name":"Reported by me","jql":"reporter = currentUser() order by created DESC","isSystem":true,"sharePermissions":[],"requiresLogin":true},{"id":-4,"name":"All issues","jql":"order by created DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-5,"name":"Open issues","jql":"resolution = Unresolved order by priority DESC,updated DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-9,"name":"Done issues","jql":"statusCategory = Done order by updated DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-3,"name":"Viewed recently","jql":"issuekey in issueHistory() order by lastViewed DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-6,"name":"Created recently","jql":"created >= -1w order by created DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-7,"name":"Resolved recently","jql":"resolutiondate >= -1w order by updated DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false},{"id":-8,"name":"Updated recently","jql":"updated >= -1w order by updated DESC","isSystem":true,"sharePermissions":[],"requiresLogin":false}]

\[{"id":-1,"name":"My open issues","jql":"assignee = currentUser() AND resolution = Unresolved order by updated DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":true},{"id":-2,"name":"Reported by me","jql":"reporter = currentUser() order by created DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":true},{"id":-4,"name":"All issues","jql":"order by created DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-5,"name":"Open issues","jql":"resolution = Unresolved order by priority DESC,updated DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-9,"name":"Done issues","jql":"statusCategory = Done order by updated DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-3,"name":"Viewed recently","jql":"issuekey in issueHistory() order by lastViewed DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-6,"name":"Created recently","jql":"created >= -1w order by created DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-7,"name":"Resolved recently","jql":"resolutiondate >= -1w order by updated DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false},{"id":-8,"name":"Updated recently","jql":"updated >= -1w order by updated DESC","isSystem":true,"sharePermissions":\[\],"requiresLogin":false}\]

0.3

0

**Comment by andrewnicols** [comment]
Sorry, but what is the point of these issues you have raised? These seem
like a bot creation.
