### ISSUE TITLE
[spam] Moodle_Script_Modules

### ISSUE THREAD

**Issue by notebook-t** [moodle/devdocs#1052]
# User Login - Moodle Academy Learning 

Clipped from: https://lang.moodle.org/user/profile.php?id=153159

## Excerpt

> What are you looking for?

What are you looking for?

* * *

Learn about Moodle's products, like Moodle LMS or Moodle Worplace, or find a Moodle Certified Service Provider.

[Moodle.com](https://moodle.com)

* * *

Our social network to share and curate open educational resources.

[MoodleNet](https://moodle.net)

* * *

Courses and programs to develop your skills as a Moodle educator, administrator, designer or developer.

[Moodle Academy](https://moodle.academy)

**Comment by andrewnicols** [comment]
@notebook-t Please stop opening junk issues. These issues are meaningless. If you are tryin gto make a meaningful contribution please let us know what you are _trying_ to do. If you continue to raise issues of this nature your account will be reported to GitHub and you will be blocked from interacting with all of our respositories.
