### ISSUE TITLE
[spam] # Info for mirror maintainers On `10th` of December [348869399] - Chromium

### ISSUE THREAD

**Issue by notebook-t** [moodle/devdocs#1062]
https://issues.chromium.org/issues/348869399

**Comment by edu2xdome** [comment]
Estilo APA 7ª Edition Re: https://legisguevarayasociados.my.canva.site/curr-culo-cv-ibarraperales-carlos-2-pdf

> https://issues.chromium.org/issues/348869399

@notebook-t
