### ISSUE TITLE
Problem with Certificate Generation in Moodle - Date Fields Not Working Properly

### ISSUE THREAD

**Issue by Bruyen72** [moodle/devdocs#1107]
### What is the issue that you're experiencing?

![Captura de tela 2024-08-27 154907](https://github.com/user-attachments/assets/f7835a7d-d611-4fc8-bcce-0b0af4dd7d2a)

I am encountering a problem with the certificate generation process in Moodle. Specifically, while trying to generate certificates using dynamic placeholders for date fields (e.g., {coursestartdate}, {courseenddate}, {completiondate}), these placeholders are not being populated with the actual dates. Instead, only the {DATE} placeholder, which reflects the current date, is working as expected.

The other placeholders return blank values or are not recognized. I need these placeholders to automatically fill with the correct start and end dates of the user's course enrollment, as well as the completion date, in order to accurately reflect the course details in the generated certificate.

Steps to Reproduce:
Set up a certificate template using placeholders like {coursestartdate}, {courseenddate}, {completiondate}.
Issue a certificate to a user who has completed a course.
The generated certificate only shows the current date (using {DATE}), while other date fields remain blank or display as placeholders.
Expected Behavior:
All placeholders related to course start, end, and completion dates should automatically populate with the appropriate dates.
Actual Behavior:
Only {DATE} populates with the current date. The placeholders for start date, end date, and completion date do not populate correctly.
Environment:
Moodle version: [ Moodle latest 4.4.1]
Plugin used for certificates: [custom Certificate]
Additional Information:
This issue affects certificate issuance for users who need accurate course details, impacting the usability and reliability of the certificate module. Any insights or solutions to ensure all date-related placeholders function correctly would be greatly appreciated.
Thank you for your assistance in resolving this issue. If any patches or adjustments can be suggested, I am open to testing them.

### Are you able to provide a patch for this?

None

**Comment by andrewnicols** [comment]
Hi,

This repository is for documentation of the core Moodle product but the issue you are reporting is with a community-contributed plugin. Unfortunately GitHub does not allow me to move this bug to the other project so I'm going to have to close this issue and ask that you raise it on 
@mdjnelson/moodle-mod_customcert instead.
