### ISSUE TITLE
[chore] Domain name selection

### ISSUE THREAD

**Issue by andrewnicols** [moodle/devdocs#159]
### What do we need to do?

We're currently trying to acquire https://moodle.dev, which is currently squatted. This may take some time.

In the mean time, it would be good to have some more identity that github.io. I have a few suggestions, all of which are currently available for a reasonable cost:

- learnmoodle.dev
- learnmoodle.io
- moodledev.io
- moodledev.info
- moodle.sh
- moodle.how
- moodle.fyi
- moodledev.how
- moodledev.fyi
- moodle.wiki

Any thoughts?

**Comment by stronk7** [comment]
No "moodle.dev" available? It it existed it would be my fav.

Said that, anything having "moodle" and "dev", has my +1 (moodledev.io > moodledev.info > moodledev.how > ...)

Ciao :-)

**Comment by andrewnicols** [comment]
> No "moodle.dev" available? It it existed it would be my fav.

That's the domain we are attempting to acquire. It is currently squatted and we are making steps to acquire it.

**Comment by wildgirl** [comment]
I vote for moodledev.io as it's short and I think we need to include 'dev' in the name.

**Comment by sarjona** [comment]
From the previous list, moodledev.io is also my favourite one (until we can switch to moodle.dev).

**Comment by ferranrecio** [comment]
For me moodledev.io is my top (apart from moodle.dev when available, of couse)

**Comment by andrewnicols** [comment]
We've bought moodledev.io as a secondary (and holding) domain while we pursue our intended domain.

**Comment by aanabit** [comment]
I also vote for moodledev.io till moodle.dev is under our control.
