### ISSUE TITLE
[repo] Move github repo to moodlehq/?

### ISSUE THREAD

**Issue by andrewnicols** [moodle/devdocs#16]
We need to move this repo to the moodlehq organisation and set it all up as appropriate.

We need to determine the most appropriate repository name for this.

**Comment by sarjona** [comment]
My proposal is to use "devdocs" for the repository name.
However, I'm not sure if it wouldn't be better to move it to moodle instead of moodlehq organisation. Thoughts?

**Comment by andrewnicols** [comment]
I'm not sure about the best organisation there - probably a question for someone like @stronk7?

Re the naming, I had wondered about `devdocs` too, but I've been pushing towards calling this `Developer resources` for branding, so I'm not sure whether `devdocs` is too focused on docs or not. Is there any difference between docs and resources enough that it matters anyway?

**Comment by andrewnicols** [comment]
Response from Eloy:

> I think Moodle is exclusively for Moodle and parts of it (libraries…) HQ for everything else (plug-ins…)
> 
> Said that, maybe it’s not crazy to put the docs in the Moodle one.

**Comment by andrewnicols** [comment]
I've moved this repo to moodle/devdocs as this seemed to be the consensus.

Closing.
