### ISSUE TITLE
[docs] Migrate Admin_settings

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#174]
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/Admin_settings

### Is this documentation specific to a Moodle version?

Unsure (Default)

### What location would you suggest in the new docs?

What about /docs/apis/other/admin-settings.md ? A new category (Other) could be created inside API guides, to place pages that are not strictly plugin types or subsystems

**Comment by sharidas** [comment]
Created PR: #327

**Comment by sarjona** [comment]
Thanks Sujith for migrating this! :-)
