### ISSUE TITLE
[docs] Migrate XMLDB_editor

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#175]
### The URL of the page on https://docs.moodle.org/dev/

XMLDB_editor

### Is this documentation specific to a Moodle version?

No

### What location would you suggest in the new docs?

/general/development/tools/xmldb.md

BTW, https://docs.moodle.org/dev/XMLDB_defining_an_XML_structure should also be reviewed to see whether it's possible to include it on the same page or not.

**Comment by sarjona** [comment]
There are several pages related to XMLDB that should also be reviewed to decide whether they should be migrated or not: https://docs.moodle.org/dev/XMLDB_Documentation (separate issues can be created for them, but I'm adding this comment here because the way we deal with all these pages might affect the final place where we migrate the XMLDB_Editor page :-) )

**Comment by abdnafees** [comment]
Hey @sarjona, can I take this one? I am working on a customized version of Moodle and I would like to get started by contributing to the docs.

**Comment by sarjona** [comment]
Hi @abdnafees!
I think you can go for it because, although Amaia assigned it one year ago, she hasn't sent anything to the repository yet ;-) 

In the following pages you'll find useful information for installing devdocs locally and migrating some pages:
- https://moodledev.io/general/documentation/contributing
- https://moodledev.io/general/documentation/installation
- https://moodledev.io/general/documentation/style-guides

Let me know if you need some help for migrating it.

**Comment by abdnafees** [comment]
Best, I am on vacation from today till Wednesday next week so will start on Thursday. I think I already have a copy of the repo and setup but I will check again. Thank you for sharing the resources. Much appreciated.

**Comment by abdnafees** [comment]
@sarjona Changes have been pushed. Thank you for sharing the resources, they were very helpful.
