### ISSUE TITLE
[docs] Migrate Output_API

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#179]
### The URL of the page on https://docs.moodle.org/dev/

Output_API

### Is this documentation specific to a Moodle version?

Unsure (Default)

### What location would you suggest in the new docs?

/docs/category/subsystems/output.md

Apart from updating the content on this page, maybe it would be good to migrate to this Output API page the content in https://docs.moodle.org/dev/Output_functions

**Comment by kabalin** [comment]
I am taking this one, can someone assign this to me?
