### ISSUE TITLE
New issue template makes it impossble to sensibly report issues with the documentation system

### ISSUE THREAD

**Issue by timhunt** [moodle/devdocs#185]
### What is the URL of the page where you experience the error?

All

### What is the issue with this page?

I am trying to report an issue with the system, but it is insisting I input a specific page URL, and then say what is wrong on that page. This just gets in the way.

### Are you able to provide a patch for this?

No (Default)

**Comment by andrewnicols** [comment]
How does filling in a bug report with complete information 'get in the way'?

We are asking for a few, small, pieces of information to try and ensure that bug reports for Moodle don't end up in the docs tracker, and to help us to categorise them more easily. We currently need:

- what kind of issue is this?
  - Documentation bug
  - Migration request
  - New documentation request
  - System error
  - Maintenance task.
- What page the error is on
- Brief description of it
- Do you have a fix?

If you think you can help us to improve any part of this, you can raise a pull request to do so. The templates are stored in https://github.com/moodle/devdocs/tree/main/.github/ISSUE_TEMPLATE and we welcome changes.

**Comment by timhunt** [comment]
System error is about the whole system, not one page, right? So the template is wrong.

Also, several of those template have a filename that does not obviously correspond to one of the choices on the first screen.

**Comment by timhunt** [comment]
So, I am looking for the template for 'System error' issues, so I can see if I understand it enough to edit it, but it is completely non-obvious which markdown file that is in.

**Comment by andrewnicols** [comment]
What would you like it to be named, instead of `repo-bug.yml`?

**Comment by andrewnicols** [comment]
I look forward to reviewing the pull request (as long as it's still a yaml file of course ;))
