### ISSUE TITLE
Github link in the template is completely pointless, and impossible to work out how to edit a page

### ISSUE THREAD

**Issue by timhunt** [moodle/devdocs#187]
### What is the URL of the page where you experience the error?

All

### What is the issue with this page?

What is the poitn of the link to https://github.com/moodle/moodle at the top of every page?

Combine that with the fact that is is non-obvious how to edit the current docs page (unlike on the old wiki), I suggest movign the 'Edit this page' link from the bottom to this slot.

(Discusssion just now in dev chat confirms that several people haev found that link in its current place.)

**Comment by timhunt** [comment]
I was suggesting replacing the existing github link, but if you can think of something better, don't let me stop you.

**Comment by andrewnicols** [comment]
I've got a partial fix to remove the GitHub link from the navbar at #199.
I will try and find a solution to add the 'Edit this page' link to the navbar, but I'm not sure when that might happen so I'll leave this issue open for now.

**Comment by andrewnicols** [comment]
Closing this now as we made the existing "Edit this page" link float in #202 in a fairly subtle way.

We may re-visit this in future, but I think for now we'll go with this.
