### ISSUE TITLE
[docs] No standard whether to write javascript, Javascript or JavaScript

### ISSUE THREAD

**Issue by lucaboesch** [moodle/devdocs#191]
### What is the URL of the page?

https://moodledev.io/general/development/policies#javascript

### What is the issue with this page?

You see the expression javascript, Javascript or JavaScript written differently through the whole of the docs.
Of course this can't be changed in the titles of historic issues, but it would be nice if it was written consistently in the manual texts.

The paragraph literally is titled "JavaScript" with the first line being "New Javascript in Moodle should be written as Vanilla javascript in the ES6 style." 🤣
Three different ways of spelling in two lines.

### Are you able to provide a patch for this?

No (Default)

**Comment by andrewnicols** [comment]
Since JavaScript is a trademark of Oracle, it should always be `JavaScript`, never:

- `javascript`
- `Javascript`
- `javaScript`
- anything else
