### ISSUE TITLE
[docs] Migrate Frankenstyle

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#223]
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/Frankenstyle

### Is this documentation specific to a Moodle version?

No

### What location would you suggest in the new docs?

general/development/policies/codingstyle/frankenstyle.md

**Comment by sharidas** [comment]
Created pull request #304

**Comment by andrewnicols** [comment]
Fixed in #304
