### ISSUE TITLE
[docs] Missing information about how to initialize a reactive component

### ISSUE THREAD

**Issue by PhMemmel** [moodle/devdocs#235]
### What is the URL of the page?

https://moodledev.io/docs/guides/javascript/reactive

### What is the issue with this page?

From the docs itself I cannot figure out how to integrate a reactive component into my moodle site/plugin directly via PHP.

In addition to the already well described way of initializing the component from a mustache file by calling a static init method there should also be an example of how to load the component with `$PAGE->requires->js_call_amd(...)` and maybe a statement about if there is a preferred way to use (or in which cases one would prefer one over the other).

### Are you able to provide a patch for this?

No (Default)

**Comment by andrewnicols** [comment]
@ferranrecio are you able to look at this?

**Comment by PhMemmel** [comment]
fixed by #236

**Comment by andrewnicols** [comment]
Thanks for the confirmation @PhMemmel
