### ISSUE TITLE
[docs] Migrate Repository plugins to /docs/apis/plugintypes/repository/

### ISSUE THREAD

**Issue by andrewnicols** [moodle/devdocs#28]
** Which page on https://docs.moodle.org/dev needs to be migrated?**

https://docs.moodle.org/dev/Repository_plugins

** Does this page need documentation specific to a Moodle version? **

Yes

** Where do you think it should be placed? **
/docs/apis/plugintypes/repository

**Comment by ferranrecio** [comment]
I am doing this one (I cannot assign myself yet)

**Comment by ferranrecio** [comment]
Branch merged.
