### ISSUE TITLE
Improve search indexing

### ISSUE THREAD

**Issue by NoelDeMartin** [moodle/devdocs#342]
### What is the issue that you're experiencing?

![image](https://user-images.githubusercontent.com/1517677/187218026-93bbb06a-794d-4155-ad38-40eba22dbfb8.png)

It seems like the current search results are favoring release notes rather than the actual documentation when searching something related to the Moodle App. Maybe this can be as easy as changing the priority in Algolia or something of the sort? (I'm not familiar with how Algolia indexes, so I'm not sure if that's even possible).

Update: It seems like this isn't limited to app documentation, some [recent comments in the forum](https://moodle.org/mod/forum/discuss.php?d=433613#p1787226) raise similar problems which happen with other APIs.

### Are you able to provide a patch for this?

No (Default)

**Comment by wojtekxtx** [comment]
@NoelDeMartin what you describe is normal since they ( moodle core team ) does not know how to do it correctly.

**Comment by NoelDeMartin** [comment]
The search settings has been updated and it works a lot better now, so I'm closing this issue.

![image](https://user-images.githubusercontent.com/1517677/226545451-be2b4970-5955-4de9-8188-3a67023fe38a.png)
