### ISSUE TITLE
[docs] Migrate Git_for_developers

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#368]
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/Git_for_developers

### Is this documentation specific to a Moodle version?

No

### What location would you suggest in the new docs?

What about /general/development/tools/git or /docs/guides/git ?

**Comment by sarjona** [comment]
Check if it's possible to migrate https://docs.moodle.org/dev/Commit_cheat_sheet too.

**Comment by andrewnicols** [comment]
In #372 @HuongNV13  suggests a target of `/docs/guides/git`, which I think is possibly more appropriate.

**Comment by timhunt** [comment]
@sarjona, I was about to migrate [Commit_cheat_sheet](https://docs.moodle.org/dev/Commit_cheat_sheet) into the new 'ABC guides' section. See https://github.com/moodle/devdocs/pull/272.

(Acutally, I am now half way through it, so I hope you are not doing it :-) )

**Comment by sarjona** [comment]
I've updated the description to add your suggestion (/docs/guides/git), although I keep thinking /general/development/tools/git fits better (the "git" doc is unrelated to the Moodle version, so I don't think it's a good idea to place it in the docs folder).

@timhunt it's great you're planning to migrate the Commit_cheat_sheet! I haven't started doing anything about this (I raised the issue to help people to identity pages easy to migrate) :-P

**Comment by sarjona** [comment]
One more thing: when the Git_for_developers page will be migrated, maybe some of the information in https://docs.moodle.org/en/Git_for_Administrators could be also added (I haven't checked/compared both, but maybe it would be better to have a common page).

**Comment by sarjona** [comment]
It would be great if the Preparing a patch section of this page can be improved with the content in https://docs.moodle.org/dev/How_to_create_a_patch and then mark How_to_create_a_patch as won't be migrated (and update current references to devdocs to the section in the Git section).

**Comment by timhunt** [comment]
Wow! nostalgia. I made [How_to_create_a_patch](https://docs.moodle.org/dev/How_to_create_a_patch) - must be more than 10 years ago. In the modern world where most people use git, I am nor sure that much of it needs to be kept.

**Comment by lucaboesch** [comment]
Wiki history even means more than 15 years ago
