### ISSUE TITLE
[docs] Migrate Git for developers

### ISSUE THREAD

**Issue by HuongNV13** [moodle/devdocs#372]
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/Git_for_developers

### What location would you suggest in the new docs?

I'm thinking about /docs/guides/git

**Comment by bozicm** [comment]
Duplicate of #368?

**Comment by andrewnicols** [comment]
Thanks @bozicm ,

Closing as duplicate.
