### ISSUE TITLE
[repo] Problem with documentation system

### ISSUE THREAD

**Issue by Abbasumaru** [moodle/devdocs#601]
### What is the issue that you're experiencing?

Exception - Call to undefined function theme_nameOfTheme\output\grade_get_course_grades()

### Are you able to provide a patch for this?

None

**Comment by sarjona** [comment]
Hi @Abbasumaru!
Thanks for reporting this. However, it isn't related to the Moodle Developers' documentation (it looks more like a bug). I would suggest you read https://moodledev.io/general/development/tracker#reporting-an-issue and report it in the Tracker.
