### ISSUE TITLE
[repo] Moodle Sessions Bug Preventing First Admin Creation on Fresh Install

### ISSUE THREAD

**Issue by data-ammar-amir-khan** [moodle/devdocs#700]
### What is the issue that you're experiencing?

While installing moodle, in https://mylms.com/user/editadvanced.php?id=2, after filling out the form to create the first admin account, the page redirects to give the following error message "Your session has most likely timed out. Please log in again.".

I have checked all the database tables to ensure they are not damaged. I have plenty of storage left on the system (approx 500 GB empty). 

No idea what the problem might be.

### Are you able to provide a patch for this?

No (Default)

**Comment by andrewnicols** [comment]
Hello,

It looks like you're trying to solve an installation issue. This is the developer documentation for Moodle and not a support site.

Please visit the Moodle forums for help on installing Moodle.
