### ISSUE TITLE
[chore] Linter warns about title level 1 even if you change it

### ISSUE THREAD

**Issue by crazyserver** [moodle/devdocs#74]
### What do we need to do?

On metadata you can specify a title that will be displayed in 3 places:

- Sidebar / menus
- HTML head title tag.
- Level 1 title on page.

If you want the title from sidebar and level 1 differ, you have to write a new level 1 title using a single hash, but then the linter warns you.

**Comment by andrewnicols** [comment]
Don't use the Markdown to change the heading, use frontmatter:

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter

```
---
title: Example title
sidebar_label: Alternate label in the sidebar
---
```

**Comment by crazyserver** [comment]
Thanks Andrew, nice tip!
