### ISSUE TITLE
Asignación de parches en el dispositivo 

### ISSUE THREAD

**Issue by alee599** [moodle/devdocs#770]
### What is the Moodle feature that needs documenting?

Aprender 

### Is this documentation specific to a Moodle version?

Yes

### Are you able to provide a patch for this?

Yes - I will create one

**Comment by sarjona** [comment]
Thanks for reporting this, @alee599!
I'm going to close this issue because it's not clear what's the proposal about ;-) Feel free to create a new one with more specific information :-)
