### ISSUE TITLE
[docs] <?php in JavaScript file apis/plugintypes/atto

### ISSUE THREAD

**Issue by leonstr** [moodle/devdocs#851]
### What is the URL of the page?

https://moodledev.io/docs/apis/plugintypes/atto#yuisrcbutton

### What is the issue with this page?

The example file for [button.js](https://moodledev.io/docs/apis/plugintypes/atto#yuisrcbutton) starts `<?php` which presumably shouldn't be there.

I can't work out how to edit the example file myself, it seems to be included using a macro.

### Are you able to provide a patch for this?

No (Default)

**Comment by andrewnicols** [comment]
Thans for that. It appears I made a mistake when writing that example. I've raised a PR to fix this in #853 which should be merged soon.
