### ISSUE TITLE
[chore] Migrate app out of `docs` directory

### ISSUE THREAD

**Issue by andrewnicols** [moodle/devdocs#86]
### What do we need to do?

Move the app docs out of the `docs` directory into its own location.

**Comment by sarjona** [comment]
I totally agree that Moodle app docs shouldn't be placed in the `docs` directory. Yesterday Andrew raised an interesting proposal: what about creating a separate folder for them (so we'll have `docs` for versioned, `general` for unversioned and `app` for the Moodle app docs)?

**Comment by andrewnicols** [comment]
I think we shoudl be fine to keep it in `/general`. The App has a different release process to Moodle and one version of the app supports multiple versions of Moodle. Users do not (usually) have much choice over which version of the app they have.
