### ISSUE TITLE
[chore] Update third-party libraries  from thirdpartylibs.xml file

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#93]
### What do we need to do?

While reviewing https://github.com/moodle/devdocs/pull/87, Andrew suggested that with the libraries we should:

- update the existing thirdpartylibs.xml files in core and add:
  - whether customisations have been made (`<customised />` if true)
  - the URL source of the library
  - the copyright owner
- create a script to parse the various thirdpartylibs files and turn them into markdown
- turn that into a Github action run weekly

**Comment by andrewnicols** [comment]
Data source update issue: https://tracker.moodle.org/browse/MDL-74697
