### ISSUE TITLE
[docs] Migrate SCSS

### ISSUE THREAD

**Issue by sarjona** [moodle/devdocs#984]
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/CSS_Coding_Style

### Is this documentation specific to a Moodle version?

Yes

### What location would you suggest in the new docs?

https://moodledev.io/docs/guides/styles

Related with https://github.com/moodle/devdocs/issues/983

**Comment by ziegenberg** [comment]
Is this a duplicate of #697?

**Comment by sarjona** [comment]
Yes, @ziegenberg! You're right! I knew there was some issue but, as I wasn't able to find it, I create it. Thanks!! :-)

I'm going to close this issue (and I also updated https://github.com/moodle/devdocs/issues/697 description because /docs/guides/styles might fit better :-)
